---
title: "DataReview_Margaret"
author: "Margaret Lindsay"
date: "2024-11-15"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(gapminder)
```

```{r}
Data <- read.csv('kc_house_data.csv', header=TRUE)

head(Data)
dim(Data)
colnames(Data)
summary(Data)
```

```{r}
#Check for NA
# NAs/No incomplete observations
Data[!complete.cases(Data),]

#Summarize variables
apply(Data[,c(3, 4, 5, 6, 7, 8, 12, 13, 14, 20, 21)], 2, mean)
apply(Data[,c(3, 4, 5, 6, 7, 8, 12, 13, 14, 20, 21)], 2, median)
```

```{r}
#Visualizations

#More than 30 bedrooms for a low price seems like an error
ggplot(Data, aes(x=bedrooms, y=price))+
  geom_point()
  labs(x="Num Bedrooms", y="Price", title="Price Against Number of Bedrooms")
  
#Bathrooms
ggplot(Data, aes(x=bathrooms, y=price))+
  geom_point()
  labs(x="Num Bathrooms", y="Price", title="Price Against Number of Bathrooms")

#Living Square Footage
ggplot(Data, aes(x=sqft_living, y=price))+
  geom_point()
  labs(x="Sqft Living", y="Price", title="Price Against Interior Square Footage")
  
#Grade
ggplot(Data, aes(x=grade, y=price))+
  geom_point()
  labs(x="Grade", y="Price", title="Price Against Grade")
  
#Condition
ggplot(Data, aes(x=condition, y=price))+
  geom_point()
  labs(x="Condition", y="Price", title="Price Against Condition")
  
#Years Built/Renovated
ggplot(Data,aes(x=yr_built)) + 
  geom_density()

ggplot(Data,aes(x=yr_built))+
  geom_histogram(binwidth = 10, color='white')

ggplot(Data,aes(x=yr_renovated)) + 
  geom_density()

ggplot(Data,aes(x=bedrooms))+
  geom_histogram(binwidth = 1, color='white')
```

```{r}
#Bedrooms--33?
Data %>% 
  count(bedrooms)

#Bathrooms--0?
Data %>% 
  count(bathrooms)

#View
Data %>% 
  count(view)

#Grade
Data %>% 
  count(grade)

#Floors
Data %>% 
  count(floors)

#Repeated IDs
id_count <- data.frame(table(Data$id))
dups <- id_count[id_count$Freq > 1,]

Data <- Data %>% 
  mutate(duplicate_id = ifelse(id %in% dups$Var1, 1, 0))

duplicates <- Data %>% 
  filter(duplicate_id == 1) %>%
  arrange(id)
duplicates
```



